#!/bin/sh
#
# An example hook script that is run after an entry is successfully added to 
# the blog.  This could be used to notify some other service that the blog
# has a new entry.
#
# $1 URL of the newly added entry
# $2 title of the newly added entry
# $3 author of the newly added entry
# $4 status of the newly added entry

# For example, let's send ourselves an email when a new entry is added.

sendmail <<EOF
From: ($3) <myself@example.com>
To: myself@example.com
Subject: New post: %2

URL: %1
status: $4

EOF

exit 0
